# Generated by Django 4.2.10 on 2024-02-26 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Автора', 'verbose_name_plural': 'Авторы'},
        ),
    ]
